config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bathrooms, shallow: true do
    resources :bookings
  end

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bathroom.rb
class Bathroom < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  mount_uploader :photo1, PhotoUploader
  mount_uploader :photo2, PhotoUploader
  mount_uploader :photo3, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bathroom
  belongs_to :user
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bathrooms
  has_many :bookings
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = " \
        bathrooms.name ILIKE :query \
        OR bathrooms.description ILIKE :query \
        OR users.name ILIKE :query \
      "
      @bathrooms = Bathroom.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @bathrooms = Bathroom.where.not(latitude: nil, longitude: nil)
    end
    @markers = @bathrooms.map do |bathroom|
      {
        lat: bathroom.latitude,
        lng: bathroom.longitude,
      }
    end
  end

  def show
    @bathroom = Bathroom.find(params[:id])
    @markers = [{
        lat: @bathroom.latitude,
        lng: @bathroom.longitude,
      }]
  end

  def new
    @bathroom = Bathroom.new
  end

  def create
    @bathroom = Bathroom.new(bathroom_params)
    @bathroom.user_id = current_user.id
    if @bathroom.save
      redirect_to bathroom_path(@bathroom)
    else
      render :new
    end
  end

  def edit
    @bathroom = Bathroom.find(params[:id])
  end

  def update
    @bathroom = Bathroom.find(params[:id])
    if @bathroom.update(bathroom_params)
      redirect_to bathroom_path(@bathroom)
    else
      render :edit
    end
  end

  def destroy
    @bathroom = Bathroom.find(params[:id])
    @bathroom.destroy
    redirect_to bathrooms_path
  end

  private

  def bathroom_params
    params.require(:bathroom).permit(:name, :size, :address, :shower_condition, :price_per_use, :description, :user_id, :photo1, :photo2, :photo3)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def show
    @booking = Booking.find(params[:id])
    @markers = [{
    lat: @booking.bathroom.latitude,
    lng: @booking.bathroom.longitude
    }]
  end

  def new
    @bathroom = Bathroom.find(params[:bathroom_id])
    @booking = Booking.new
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :edit
    end
  end

  def create
    @bathroom = Bathroom.find(params[:bathroom_id])
    @booking = Booking.new(booking_params)
    @booking.bathroom_id = @bathroom.id
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def booking_params
    params.require(:booking).permit(:bathroom_id, :user_id, :start_time, :end_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  # configure this after the routes is finalized
  # skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fa_icon(name)
    content_tag(:i, '', class: ['fa', name])
  end
end

app/views/bathrooms/_form.html.erb
<div class="form-container">
  <div class="form-card">
    <div class="back-btn" id="back-fixed">
      <%= link_to request.referer.present? ? request.referer : default_path do %>
        <%= fa_icon 'fa-backward' %>
      <% end %>
    </div>
    <div class="form-row">
      <div class="form-title">
        <h2>New Bathroom</h2>
      </div>
      <div class="col col-xs-12 col-sm-12">
        <%= simple_form_for (@bathroom) do |bath| %>
          <%= bath.error_notification %>
          <%= bath.error_notification message: bath.object.errors[:base].to_sentence if bath.object.errors[:base].present? %>
          <div class="form-inputs">
            <%= bath.input :name %>
            <%= bath.input :size %>
            <%= bath.input :address %>
            <%= bath.input :description %>
            <%= bath.input :price_per_use%>
            <%= bath.label :shower %>
            <%= bath.collection_radio_buttons :shower_condition, [[true, 'Yes'], [false, 'No']], :first, :last  %>
            <%= bath.input :photo1 %>
            <%= bath.input :photo1_cache, as: :hidden %>
            <%= bath.input :photo2 %>
            <%= bath.input :photo2_cache, as: :hidden %>
            <%= bath.input :photo3 %>
            <%= bath.input :photo3_cache, as: :hidden %>
          </div>
          <div class=“form-actions”>
            <%= bath.submit "Submit" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bathrooms/create.html.erb
<h1>Bathroom#create</h1>
<p>Find me in app/views/bathroom/create.html.erb</p>

app/views/bathrooms/edit.html.erb
<h1>Bathroom#edit</h1>

<%= render 'form' %>

app/views/bathrooms/index.html.erb
<div class="search-bar">
  <%= form_tag bathrooms_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a bathroom"
  %>
  <% end %>
</div>

<div class="main-container">
  <div class="cards-container">
    <div class="bathroom-index-row">
    <% @bathrooms.each do |bathroom| %>
      <%= link_to bathroom_path(bathroom) do %>
        <div class="col-xs-12 col-sm-6">
          <% if bathroom.photo1? %>
            <div class="card bathroom-index-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bathroom.photo1, crop: :fill %>');">
          <% else %>
            <div class="card bathroom-index-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://st.hzcdn.com/simgs/cf3111130426c707_4-1308/traditional-bathroom.jpg');">
          <% end %>

            <div class="card-category"><%= bathroom.name %></div>
            <div class="card-description">
              <p><%= bathroom.address %></p>
              <p>$<%= bathroom.price_per_use %></p>
              <p><%= bathroom.user.name %>'s favourite bathroom</p>
            </div>
            <%= link_to user_path(bathroom.user) do %>
              <% if bathroom.user.photo? %>
                <%= cl_image_tag bathroom.user.photo, class: "card-user", height: 40, width: 40 %>
              <% else %>
                <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>

  <div class="home-map"
    id="map"
    style="width: 100%;"
    data-markers="<%= @markers.to_json %>"
  ></div>
</div>

app/views/bathrooms/new.html.erb
<%= render "form" %>

app/views/bathrooms/show.html.erb
<% if @bathroom.photo1? %>
  <div class="banner bathroom-show-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path @bathroom.photo1, crop: :fill %>');">
<% else %>
  <div class="banner bathroom-show-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://st.hzcdn.com/simgs/cf3111130426c707_4-1308/traditional-bathroom.jpg');">
<% end %>
  <div>
    <div><h1><%= @bathroom.name %></h1></div>
    <div><h3>$<%= @bathroom.price_per_use %></h3></div>
  </div>
</div>

<div class="main-container">
  <div class="info-container">
    <div class="info bathroom-info">
      <div>
        <h3>Address</h3>
        <div class="description">
          <p><%= @bathroom.address %></p>
        </div>
      </div>
      <div>
        <h3>Size</h3>
        <div class="description">
          <p><%= @bathroom.size %> square meters</p>
        </div>
      </div>
      <div>
        <h3>Has shower?</h3>
        <% if @bathroom.shower_condition == true %>
          <div class="description">
            <p>Has shower, enjoy!</p>
          </div>
        <% else %>
          <div class="description">
            <p>Sorry, no shower.</p>
          </div>
        <% end %>
      </div>
      <div>
        <h3>Description</h3>
        <div class="description">
          <p><%= @bathroom.description %></p>
        </div>
      </div>
    </div>
    <div class="buttons">
      <% if current_user.id == @bathroom.user_id %>
        <div class = "btn-medium">
          <%= link_to "Edit the Bathroom", edit_bathroom_path %>
        </div>
        <div class = "btn-medium">
          <%= link_to "Delete this Bathroom", bathroom_path(@bathroom.id), method: :delete,  data: { confirm: "Are you sure?" }  %>
        </div>
      <% else %>
        <div class="btn-medium">
          <%= link_to "Make a Booking", new_bathroom_booking_path(@bathroom) %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="show-map" id="map"
    data-markers="<%= @markers.to_json %>">
  </div>
</div>

app/views/bookings/_form.html.erb
<div class="form-container">
  <div class="form-card">
    <div class="back-btn" id="back-fixed">
      <%= link_to request.referer.present? ? request.referer : default_path do %>
        <%= fa_icon 'fa-backward' %>
      <% end %>
    </div>
    <div class="form-row booking-form-row">
      <div class="form-title">
        <h2>New Booking</h2>
      </div>
      <div class="col col-xs-12 col-sm-12">
        <%= simple_form_for ([@bathroom, @booking]) do |book| %>
          <%= book.error_notification %>
          <%= book.error_notification message: book.object.errors[:base].to_sentence if book.object.errors[:base].present? %>
          <div class="form-inputs">
            <%= book.input :start_time, as: :datetime_picker %>
            <%= book.input :end_time, as: :datetime_picker %>
          </div>
          <div class="form-actions booking-form-button">
            <%= book.submit "Submit!" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Change your booking!</h1>
<%= render 'form' %>

app/views/bookings/index.html.erb
<div class="user-prof">
  <img src="raymond-prof" class="avatar-large">
  <div class="user-info">
    <h2>Raymond Yan</h2>
    <p> 19, Henan</p>
  </div>
</div>

<div class="manage-container">
  <div class="manage-header">
    <div class="tab book-tab">
      <a href="#" class="tab-active"><strong>My bookings</strong></a>
    </div>
    <div class="tab-text">
      <a href="#" class="tab"><strong>My listings</strong></a>
    </div>
  </div>
  <ul class="bookings">
    <% @bookings.each do |t| %>
    <li>
      <% owner = User.find(t.user_id) %>
      <%= owner.name %>
      <% bathroom = Bathroom.find(t.bathroom_id) %>
      <%= bathroom.address %>
      <%= t.start_time %>
      <%= t.end_time %>
    </li>
    <% end %>
  </ul>

</div>

app/views/bookings/list.html.erb
<div class="user-prof">
  <img src="raymond-prof" class="avatar-large">
  <div class="user-info">
    <h2>Raymond Yan</h2>
    <p> 19, Henan</p>
  </div>
</div>

<div class="manage-container">
  <div class="manage-header">
    <div class="tab book-tab">
      <a href="#" class="tab-active"><strong>My bookings</strong></a>
    </div>
    <div class="tab-text">
      <a href="#" class="tab"><strong>My listings</strong></a>
    </div>
  </div>
  <ul class="bookings">
    <% all_book = current_user.bookings  %>
    <% all_book do |t| %>
    <li>
      <% owner = User.find(t.bathroom_id) %>
      <%= owner.name %>
    </li>
  </ul>

</div>

app/views/bookings/new.html.erb
<%= render "form" %>

app/views/bookings/show.html.erb
<% bathroom_owner_id = Bathroom.find(@booking.bathroom_id).user_id %>
<% owner = User.find(bathroom_owner_id)  %>
<div class= "show-container">
  <div class= "confirm-card">
    <div class="contain-photo">
      <% if owner.photo? %>
        <div class="large-ava">
          <%= cl_image_tag owner.photo, class: "help" %>

        </div>
      <% else %>
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="large-ava">
      <% end %>
    </div>
    <div class="confirm-message">
      <% cur_bath = Bathroom.find(@booking.bathroom_id) %>
      <% if Bathroom.find(@booking.bathroom_id).user_id == current_user.id %>
        <% booker = current_user.name %>
        <h4><%= "Your bathroom has been booked by #{booker}" %></h4>
        <% else %>
        <h4><%= "Your booking with #{owner.name} has been confirmed!" %></h4>
      <% end %>
    </div>
  </div>
  <div class="detail-container">
    <h3><strong>Trip Details</strong></h3>
    <div class="check-container">
      <div class="check">
        <h3 class="penis">Check in</h3>
        <p><strong><% in_time = @booking.start_time %><%= in_time.strftime("%a, %b %d ")%></strong></p>
        <p><strong><% in_time = @booking.start_time %><%= in_time.strftime("%I:%M%p ")%></strong></p>
      </div>
      <div class="check">
        <h3 class="penis">Check out</h3>
        <p><strong><% out_time = @booking.end_time %><%= out_time.strftime("%a, %b %d ")%></strong></p>
        <p><strong><% out_time = @booking.end_time %><%= out_time.strftime("%I:%M%p ")%></strong></p>
      </div>
    </div>
    <div class="bath-name">
      <h3><%= cur_bath.address %></h3>
    </div>
  </div>
  <div class="contain-butt">
    <div class="large-butt" >
      <%= link_to request.referer.present? ? request.referer : default_path do %>
        <%= fa_icon 'fa-backward' %>
      <% end %>
    </div>
    <div class="large-butt" id="cancel-butt">
      <%= link_to booking_path, method: :delete,  data: { confirm: "Are you sure?" } do %>
        <%= fa_icon 'fa-times-circle' %>
      <% end %>
    </div>
    <div class="large-butt">
      <%= link_to edit_booking_path(@booking) do %>
        <%= fa_icon 'fa-edit' %>
      <% end %>
    </div>
  </div>

  <div class="container-map">
    <div class="book-map" id="map"
      data-markers="<%= @markers.to_json %>">
    </div>
  </div>
</div>






<!-- <p><%= @booking.start_time %></p>
<h2>End time</h2>
<p><%= @booking.end_time %></p>
<h2>Bathroom name</h2>
<p><%= @booking.id %></p>
<h2>Address</h2>
<p><%= @booking.bathroom.address %></p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= render 'shared/navbar' %>

<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Milonga|Montserrat:100,00" rel="stylesheet">
    <title>BathroomJoy | Don't Piss Yourself</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="page-container">
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['AIzaSyDGUfjS5-6iTex7AMAktWROhQ6LgZVdgAQ']}" %>
    <%= javascript_pack_tag "map" %>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class= "banner", style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'background.jpg' %>);">
  <div class="banner-content home-banner-content">
    <h1>Find Your Dream Bathroom</h1>
    <h3 id="home-page-h3">ANYWHERE, ANYTIME</h3>
    <div class="container">
      <div class="custom topBotomBordersOut">
        <%= link_to new_bathroom_path do %>
          <p>Host Your Bathroom</p>
        <% end %>
        <%= link_to bathrooms_path do %>
          <p>Book a Bathroom</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="wrapper">
  <div class='home-page-row'>
    <h2 id="home-page-h2">Nearby you now</h2>
    <% Bathroom.all.each do |bathroom| %>
      <div class = "col-sx-12 col-sm-4">
        <%= link_to bathroom_path(bathroom) do %>
          <% if bathroom.photo1? %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bathroom.photo1, crop: :fill %>');">
          <% else %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://st.hzcdn.com/simgs/cf3111130426c707_4-1308/traditional-bathroom.jpg');">
          <% end %>
          <div class="card-category">Popular</div>
          <div class="card-description">
            <h4><%= bathroom.name %></h4>
          </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div id="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <div class="custom topBotomBordersOut">
      <%= link_to root_path do %>
        <p class="navbar-wagon-item navbar-wagon-link">Home</p>
      <% end %>
      <%= link_to bathrooms_path do %>
        <p class="navbar-wagon-item navbar-wagon-link">Browse</p>
      <% end %>
    </div>

    <% if user_signed_in? %>
    <!-- After signing up -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo? %>
            <div id="navbar-wagon-menu" data-toggle="dropdown">
              <%= cl_image_tag current_user.photo , class: "avatar dropdown-toggle"%>
            </div>
          <% else %>
            <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <div class="link-box">
              <%= link_to user_path(current_user.id) do %>
                <li>Profile</li>
              <% end %>
            </div>
            <div class="link-box">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <li>Sign Out</li>
              <% end %>
            </div>

          </ul>
        </div>
      </div>
    <% else %>
      <div class="navbar-wagon-item">
        <%= link_to new_user_session_path do %>
          <span class="btn btn-clear">
            LOG IN
          </span>
        <% end %>
        <%= link_to new_user_registration_path do %>
          <span class="btn btn-clear btn-signup">
            SIGN UP
          </span>
        <% end %>
      </div>
    <% end %>

  </div>
              <!--%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <!-%= t(".sign_out", default: "Log out") %>
              <!% end %>
            </li>
          </ul>
        </div>
      </div>
    <! % else % -->
      <!-- Login link (when logged out) -->
      <!--%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <!-% end %>
  </div>

  <!- Dropdown list appearing on mobile only -->
<!--   <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/users/_show-old.html.erb
  <div class="custom topBotomBordersOut btn-black-out">
    <%= link_to new_bathroom_path do %>
      <p>New Bathroom</p>
    <% end %>
  </div>

  <div class="my-bookings">
    <h2>My Bookings</h2>
    <% @user.bookings.each do |booking| %>
      <%= link_to booking_path(booking.id) do %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
            <div class="card-category">My booking</div>
            <div class="card-description">
              <p><%= booking.start_time %></p>
              <p><%= booking.end_time %></p>
              <p><%= booking.bathroom.name %></p>
              <p><%= booking.bathroom.address %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <br>

  <div class="my-bathrooms">
    <h2>My Bathrooms</h2>
    <% @user.bathrooms.each do |bathroom| %>
      <%= link_to bathroom_path(bathroom) do %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
            <div class="card-category">My bathroom</div>
            <div class="card-description">
              <p><%= bathroom.name %></p>
              <p><%= bathroom.address %></p>
              <p><%= bathroom.size %> squre meters</p>
              <p><%= bathroom.shower_condition %></p>
              <p>$<%= bathroom.price_per_use %></p>
              <p><%= bathroom.description %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/users/show.html.erb
<div class="container">
<span class="bckg"></span>
<main>
  <article class="larg">

    <div>
      <h3>My Bookings <span class="entypo-down-open"><%= fa_icon 'fa-chevron-down' %></span></h3>
        <div class="user-content">
          <% @user.bookings.each do |booking| %>
            <%= link_to booking_path(booking.id) do %>
              <% if booking.bathroom.photo1? %>
                <div class="profile-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path booking.bathroom.photo1, crop: :fill %>');">
              <% else %>
                <div class="profile-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://st.hzcdn.com/simgs/cf3111130426c707_4-1308/traditional-bathroom.jpg');">
              <% end %>
              <% if booking.start_time? %>
                <div class="profile-card-time">
                  <%= booking.start_time.strftime("%H:%M  %b %d %Y") %>
                  <% diff = booking.end_time - booking.start_time %>
                   |
                  <% if diff/60 >= 60 && diff/60 < 120 %>
                    <%= (diff/60/60).ceil %> hr
                  <% elsif diff/60 >= 120 %>
                    <%= (diff/60/60).ceil %> hrs
                  <% else %>
                    <%= (diff/60).ceil %> mins
                  <% end %>
                </div>
              <% else %>
                <div class="profile-card-time">
                  Sorry, you did not choose a start time.
                </div>
              <% end %>
                  <div class="profile-card-description">
                    <p><%= booking.bathroom.name %> AT</p>
                    <br>
                    <p><%= booking.bathroom.address %></p>
                  </div>
                </div>
            <% end %>
          <% end %>
      </div>
    </div>
    <div>
      <h3>My Bathrooms <span class="entypo-down-open"><%= fa_icon 'fa-chevron-down' %></span></h3>
      <div class="user-content">
        <% @user.bathrooms.each do |bathroom| %>
          <%= link_to bathroom_path(bathroom) do %>
              <% if bathroom.photo1? %>
                <div class="profile-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bathroom.photo1, crop: :fill %>');">
              <% else %>
                <div class="profile-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://st.hzcdn.com/simgs/cf3111130426c707_4-1308/traditional-bathroom.jpg');">
              <% end %>
                <div class="profile-card-room-name">
                  <p><%= bathroom.name %></p>
                </div>
                <div class="profile-card-address">
                  <p><%= bathroom.address %></p>
                  <p>$<%= bathroom.price_per_use %></p>
                </div>
              </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </article>
</main>
</div>